services:
  
  ollama-service:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - 11434:11434

  who-is-jean-luc-picard:
    build:
      context: .
      dockerfile: Dockerfile.genai
    command: go run main.go
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
      - LLM=qwen2.5:0.5b
    volumes:
      - ./:/app
    depends_on:
      ollama-service:
        condition: service_started

